import Head from "next/head";
import Header from "../components/Header";
import Image from "next/image";

import teamMembers from "../data/teamMembers.json";
import faqs from "../data/faqs.json";
import whatsWrong from "../data/whatsWrong.json";

export const getStaticProps = async () => {
  return {
    props: {
      teamMembers: teamMembers,
      faqs: faqs,
      whatsWrong: whatsWrong,
    },
  };
};

export default function Home({ teamMembers, faqs, whatsWrong }) {
  return (
    <>
      <Head>
        <title>dgMenu</title>
        <meta name="description" content="Generated by create next app" />
        <body
          className="bg-zinc-900 text-white bg-no-repeat bg-top lg:bg-left-top pb-20"
          style={{ backgroundImage: "url('img/light.avif')" }}
        ></body>
      </Head>
      <Header></Header>

      <section id="landing" className="relative">
        <main className="box flex flex-col text-center py-32 lg:py-60 gap-8 items-center">
          <h1 className="text-7xl lg:text-8xl font-black leading-none max-w-[17ch]">
            Always serve the
            <span className="rgb-gradient"> freshest</span> menu.
          </h1>
          <p className="text-xl lg:text-2xl text-zinc-300">
            Display the most up-to-date menu to your customers with dgMenu.
          </p>
          <div className="flex gap-4 justify-center items-center">
            <a
              href="#"
              className="btn border-rgb-green hover:bg-rgb-green hover:text-black"
            >
              Learn more
            </a>
            <a href="#" className="btn border-rgb-purple hover:bg-rgb-purple">
              Get in touch
            </a>
          </div>
        </main>
        <a
          href="#wrong"
          className="absolute bottom-0 right-1/2 p-5 translate-x-1/2"
        >
          <i className="fas fa-chevron-down text-center animate-bounce"></i>
        </a>
      </section>

      <section id="wrong">
        <div className="box py-28">
          <h2 className="text-center lg:text-left text-4xl lg:text-5xl font-black">
            What's <span className="rgb-gradient">wrong</span> with your menu?
          </h2>
          <div className="grid lg:grid-cols-3 mt-20 gap-12 text-center lg:text-left">
            {whatsWrong.map((feature, i) => (
              <div className="space-y-2" key={i}>
                <span className="text-rgb-green text-4xl">
                  <i className={feature.class}></i>
                </span>
                <h3 className="font-bold text-3xl">{feature.title}</h3>
                <p className="mx-auto lg:mx-0 max-w-[30ch] text-zinc-300">
                  {feature.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="faq">
        <div className="box py-28">
          <h2 className="text-center lg:text-left text-4xl lg:text-5xl font-black">
            <span className="rgb-gradient">Frequently</span> asked questions
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 mt-20 gap-12">
            {faqs.map((faq, i) => (
              <div key={i}>
                <h4 className="text-2xl font-black">{faq.q}</h4>
                <p>{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="clients">
        <div className="box py-28">
          <h2 className="text-center lg:text-left text-4xl lg:text-5xl font-black">
            From our
            <span className="rgb-gradient"> clients</span>
          </h2>
          <div className="flex flex-col lg:flex-row mt-20 gap-12 justify-center items-start">
            <div>
              <Image
                alt="Saltt website screenshot"
                title="Saltt website screenshot"
                src="/img/clients/saltt-ss.png"
                width={500}
                height={350}
                layout="intrinsic"
              />
            </div>
            <div className="flex flex-col  justify-start gap-5 items-center lg:items-start text-center lg:text-left mx-auto lg:mx-0">
              <Image
                alt="Saltt Logo"
                title="Saltt Logo"
                src="/img/clients/saltt-logo.png"
                width={120}
                height={45}
                layout="intrinsic"
              />
              <q className="text-2xl font-bold">
                The boys have done a good job.
              </q>
              <div>
                <h3 className="font-black">Dan Vaz</h3>
                <span className="italic">Proprietor, Saltt Kitchen 'n Bar</span>
              </div>
              <h4>
                Visit:{" "}
                <a
                  rel="noreferrer"
                  className="text-rgb-green underline hover:text-rgb-purple transition-colors duration-300 font-bold"
                  href="//saltt.cf"
                  target="_blank"
                >
                  www.saltt.cf
                </a>
              </h4>
            </div>
          </div>
        </div>
      </section>

      <section id="team">
        <div className="box py-28">
          <h2 className="text-center lg:text-left text-4xl lg:text-5xl font-black">
            Meet the
            <span className="rgb-gradient"> team</span>
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 mt-20 gap-12">
            {teamMembers.map((member) => (
              <div
                className="space-y-2 flex items-center
                flex-col text-center"
                key={member.name}
              >
                <Image
                  src={member.img}
                  alt={member.name}
                  title={member.name}
                  className="h-40"
                  width={160}
                  height={160}
                />
                <h3 className="text-3xl font-black">{member.name}</h3>
                <p>{member.roll}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
